---
- name: Install dependencies
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - fakeroot
    - binutils

- name: Install from aur
  aur:
    name: visual-studio-code-bin
    user: "{{ aur_user }}"
