---
# tasks file for pacaur

- name: All root
  become: yes
  block:
    - name: "[aur] check dependencies"
      pacman:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - shadow

    - name: "[aur] check aur installer"
      pacman:
        name: "{{ aur_installer }}"
        state: present
        update_cache: yes
      when: aur_installer is defined

    - name: "[aur] create user"
      user:
        name: "{{ aur_user }}"
        state: present
        shell: /bin/nologin
        home: /var/lib/aurman
        system: yes

    - name: add to sudoers
      lineinfile:
        line: "{{ aur_user }} ALL=(ALL) NOPASSWD: ALL"
        path: "/etc/sudoers"

- name: "[aur] test install from aur"
  aur:
    name: openssl
    user: "{{ aur_user }}"
